// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAD5TSXF97kV0PrD7LbzNjYQbx_6fczhE',
    appId: '1:154945386773:web:f3c26bf72140a12138511c',
    messagingSenderId: '154945386773',
    projectId: 'tree-app-project',
    authDomain: 'tree-app-project.firebaseapp.com',
    storageBucket: 'tree-app-project.appspot.com',
    measurementId: 'G-LQYZ304RTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC68IIdt3lzx3GERlwA8k-dHivXNOjkYjs',
    appId: '1:154945386773:android:369400a9f4e5ccb038511c',
    messagingSenderId: '154945386773',
    projectId: 'tree-app-project',
    storageBucket: 'tree-app-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzdysgLKLCSCy8mRQg05pQg5H1Hqfreyk',
    appId: '1:154945386773:ios:f7609fd2ad0d5b4738511c',
    messagingSenderId: '154945386773',
    projectId: 'tree-app-project',
    storageBucket: 'tree-app-project.appspot.com',
    iosBundleId: 'com.example.allTeckstack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzdysgLKLCSCy8mRQg05pQg5H1Hqfreyk',
    appId: '1:154945386773:ios:2bf579c20067d15338511c',
    messagingSenderId: '154945386773',
    projectId: 'tree-app-project',
    storageBucket: 'tree-app-project.appspot.com',
    iosBundleId: 'com.example.allTeckstack.RunnerTests',
  );
}
